# This file is a template, and might need editing before it works on your project.
# Official docker image.
stages:
  - binaries
  - containers

image: docker:latest
# services:
#   - docker:dind

# before_script:
#   - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  #env: ["PROJECT_ROOT=github.com/danisla/kubernetes-tproxy"]
    # - env
    # - wget -qO- https://github.com/tmate-io/tmate/releases/download/2.2.1/tmate-2.2.1-static-linux-amd64.tar.gz | tar xvz -C /tmp -f - 
    # - echo mv /tmp/tmate-2.2.1-static-linux-amd64/tmate /usr/local/bin
    # - echo chmod +x /usr/local/bin/tmate

build-initializer:
  stage: binaries
  image:
    name: 'gcr.io/cloud-builders/go:alpine'
    entrypoint: [""]
  script:
    - export CI_GITLAB_FQDN=$(echo $CI_PROJECT_URL | sed sXhttps\\://XX | sed sX\/.*\$XX)
    # TODO: copy source kubernetes-tproxy into /go/src/gitlab.ii.coop
    - ln -s /builds /go/src/$CI_GITLAB_FQDN
    - export GOPATH=/go
    # - cd /go/src/$CI_GITLAB_FQDN/$CI_PROJECT_PATH
    # - go get ./...
    # - go install ./cmd/tproxy-initializer/
    # - go install ./cmd/tproxy-podwatch/
    # - pwd
    # - find .
    # - sleep 99999999
    - apk add --no-cache openssh alpine-sdk automake autoconf libevent-dev ncurses-dev msgpack-c-dev libssh-dev
    - cd /root
    - git clone https://github.com/nviennot/tmate
    - cd tmate ; ./autogen.sh && ./configure && make install
    - ssh-keygen -t rsa -f /root/.ssh/id_rsa -N ''
    - uname -a ; free -m ; df; ip addr ; ip route
    - ldd /usr/local/bin/tmate
    - ls -la /usr/local/bin
    # - pkg update ; pkg add file
    - cd /go/src/$CI_GITLAB_FQDN/$CI_PROJECT_PATH
    - tmate -S /tmp/tmate.sock new-session -d
    - tmate -S /tmp/tmate.sock wait tmate-ready
    - tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}'

contain-sidecar:
  stage: containers
  script:
    - cd sidecar
    - docker build --pull -t "tproxy-sidecar:$CI_COMMIT_REF_SLUG" .
    - docker push "tproxy-sidecar:$CI_COMMIT_REF_SLUG"

contain-initializer:
  stage: containers
  script:
    - docker build -f Dockerfile-initializer --pull -t "tproxy-initializer:$CI_COMMIT_REF_SLUG" .
    - docker push "tproxy-initializer:$CI_COMMIT_REF_SLUG"

contain-podwatch:
  stage: containers
  script:
    - docker build -f Dockerfile-podwatch --pull -t "tproxy-podwatch:$CI_COMMIT_REF_SLUG" .
    - docker push "tproxy-podwatch:$CI_COMMIT_REF_SLUG"

