apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tproxy.serviceAccountName }}-secret
  annotations:
    kubernetes.io/service-account.name: {{ .Values.tproxy.serviceAccountName }} 
type: kubernetes.io/service-account-token
